### ISSUE TITLE
v0.14.0 publish broken

### ISSUE THREAD

**Issue by andrewheadricke** [whyrusleeping/gx#217] opened 2018-10-26 01:21 UTC
I just updated to gx v0.14.0 and it appears to be broken.  

`gx publish` results with

`Error: publishing: <nil>`

Downgraded to v0.13.0 and it works

**Comment by schomatis** [comment] 2018-10-26 03:51
Hey @andrewheadricke, could you provide more context about the error? What were you trying to publish?

**Comment by andrewheadricke** [comment] 2018-10-26 03:55
I just created a new project with `gx init` and put in some minimal settings, then added a file and tried to publish it.  I also tried to re-publish older packages that have always worked, same error.

I'm on linux, using precompiled gx downloaded from dist.ipfs.io

**Comment by schomatis** [comment] 2018-10-26 04:13
Yes, I can reproduce the error with the [linux binary](https://dist.ipfs.io/gx/v0.14.0/gx_v0.14.0_linux-amd64.tar.gz) which right off the bat is reporting a `0.0.0` version. The `git` version (e.g., `89338e5` that corresponds with `v0.14.0`) is working fine. Not sure who can help with `dist.ipfs.io` so I'll just tag @Stebalien and hope for the best. Thanks for reporting this!

**Comment by Stebalien** [comment] 2018-10-26 11:11
I can. This is due to a bug in go-ipfs-api that has already been fixed (didn't realize it made it into gx). I'll cut a release.

**Comment by Stebalien** [comment] 2018-10-31 17:23
I've cut a 0.14.1 release so this should be fixed.

**Closed by Stebalien** 2018-10-31 17:23 UTC
Labels: bug
