### ISSUE TITLE
knownhosts missing?

### ISSUE THREAD

**Issue by EmbeddedAndroid** [whyrusleeping/gx#214] opened 2018-10-06 08:34 UTC
New to go, so I may have screwed something up but trying to install git-remote-ipld and getting this:

```
gx-go rewrites
go get ./...
package gx/ipfs/Qme1boxspcQWR8FBzMxeppqug2fYgYc15diNWmqgDVnvn2/go-crypto/ssh/knownhosts: unrecognized import path "gx/ipfs/Qme1boxspcQWR8FBzMxeppqug2fYgYc15diNWmqgDVnvn2/go-crypto/ssh/knownhosts" (import path does not begin with hostname)
Makefile:9: recipe for target 'deps' failed
make: *** [deps] Error 1
```
And indeed, no link found when trying to access that file. 

https://gateway.ipfs.io/ipfs/Qme1boxspcQWR8FBzMxeppqug2fYgYc15diNWmqgDVnvn2/go-crypto/ssh/knownhosts

**Comment by schomatis** [comment] 2018-10-06 14:59
I can reproduce this problem but this issue seems to be related to the `Makefile` process rather than the `gx-go` tool itself so I'm going to close this for tracking purposes (feel free to keep asking questions here but I'd recommend submitting an issue in the `git-remote-ipld` repo).

**Closed by schomatis** 2018-10-06 14:59 UTC

**Comment by schomatis** [comment] 2018-10-06 15:08
Additional reference to provide to the `git-remote-ipld`:

```
gx deps --tree

[...]
├─ go-git.v4                     QmSVCWSGNwq9Lr1t4uLSMnytyJe4uL7NW7jZ3uas5BPpbX 1.0.4
│  ├─ go-context                 QmX6DhWrpBB5NtadXmPSXYNdVvuLfJXoFNMvUMoVvP5UJa 0.0.0
│  │  └─ go-net                  QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt 0.0.0
│  │     ├─ go-text              Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ 0.0.0
│  │     └─ go-crypto            Qme1boxspcQWR8FBzMxeppqug2fYgYc15diNWmqgDVnvn2 0.0.0

             ^^^ old `go-crypto` version that doesn't match the other versions
             of this dependency (`QmW7VUmS`)
[...]
```

**Comment by EmbeddedAndroid** [comment] 2018-10-06 17:55
Thanks for the quick turn around, reported https://github.com/ipfs-shipyard/git-remote-ipld/issues/17
